It 3223 user moves into checkout
dorim-group/autotests-price pull request #11
Opened 2024-10-14 13:08 UTC by Snowfox21

Добавлен тест, добавлены селекторы, ссылки

2024-10-16 09:27 UTC, tkachukanton requested changes

2024-10-16 09:27 UTC, tkachukanton commented on cypress/pages/checkout.js
> +returnToCartBtn: '["data-testid="edit-cart-btn"]',
синтаксис поправь, так работать вообще не должно если этот селектор где то используется

2024-10-16 09:27 UTC, tkachukanton commented on cypress/pages/checkout.js
> +const productSelectionPage = new mainPage();
этот экземпляр класса лучше перенести в сам метод, если используется всего раз тут

2024-10-16 09:27 UTC, tkachukanton commented on cypress/pages/checkout.js
> +            expect(response.items[0].items[0].cart_offer).to.have.property('name', "auto_test_product");
давай заменим название продукта тут на переменную, в случае ее изменения будет легче везде изменить и более читаемо

2024-10-16 09:27 UTC, tkachukanton commented on cypress/pages/checkout.js
> +            expect(response).to.have.property('items').and.to.be.an('array');
давай добавим проверку на статус код тут
expect(response).to.have.property('statusCode', 200)

2024-10-16 09:27 UTC, tkachukanton commented on cypress/pages/checkout.js
> +import mainPage from "./product-selection";
импортируем и используем productSelectionPage

2024-10-16 10:04 UTC, Snowfox21 commented
@tkachukanton Исправил все замечания

2024-10-17 06:07 UTC, tkachukanton commented on cypress/pages/checkout.js
> +  returnToCartBtn: '["data-testid="edit-cart-btn"]',
returnToCartBtn: '[data-testid="edit-cart-btn"]',

2024-10-17 07:42 UTC, tkachukanton approved these changes

2024-10-17 07:42 UTC, merged